version: '3.8'
services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

  db_server:
    build: ./
    container_name: db-server
    environment:
      - MODE=prod
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./:/app/
    ports:
      - "5001:5101"
    command: sh scripts/run.sh
